### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by MuwuM** [Wandalen/BufferFromFile#21] opened 2020-08-15 22:49 UTC
When I try to install this package on my Windows 10 machine I only get the following error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferfromfile@0.4.214 install: `will .build install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferfromfile@0.4.214 install script.`
```

Tested with
- 0.4.214
- 0.4.213
- 0.4.212

Am I missing some dependencies? could not fine any in the readme

**Comment by volodymyrmigdal** [comment] 2020-10-26 10:23
Hello. Thanks for reporting this problem. The problem is fixed in version 0.4.223. 
Please try `npm add bufferfromfile@alpha` or `npm install bufferfromfile@alpha`.

**Closed** 2020-10-28 16:53 UTC
Labels: bug
